# Master Header 並び順
# Product Master

import pandas as pd

def type():
    type_p =({'Process Mode': str,
        'Master ID': str,
        'Subsidiary Code': str,
        'Inner Code': str,
        'Product Code': str,
        'Stock / MTO': str,
        'Product Component': str,
        'Production LT': float,
        'Min Qty of Big Order': float,
        'Max Qty of Big Order': float,
        'Supplier Code of BO': str,
        'Slide Qty 1': float,
        'Slide Sales Pc/Unit 1': float,
        'Slide Purchase Pc/Unit 1': float,
        'Slide Production LT 1': float,
        'Slide Days TS 1': float,
        'Slide Qty 2': float,
        'Slide Sales Pc/Unit 2': float,
        'Slide Purchase Pc/Unit 2': float,
        'Slide Production LT 2': float,
        'Slide Days TS 2': float,
        'Slide Qty 3': float,
        'Slide Sales Pc/Unit 3': float,
        'Slide Purchase Pc/Unit 3': float,
        'Slide Production LT 3': float,
        'Slide Days TS 3': float,
        'Slide Qty 4': float,
        'Slide Sales Pc/Unit 4': float,
        'Slide Purchase Pc/Unit 4': float,
        'Slide Production LT 4': float,
        'Slide Days TS 4': float,
        'Slide Qty 5': float,
        'Slide Sales Pc/Unit 5': float,
        'Slide Purchase Pc/Unit 5': float,
        'Slide Production LT 5': float,
        'Slide Days TS 5': float,
        'Slide Qty 6': float,
        'Slide Sales Pc/Unit 6': float,
        'Slide Purchase Pc/Unit 6': float,
        'Slide Production LT 6': float,
        'Slide Days TS 6': float,
        'Slide Qty 7': float,
        'Slide Sales Pc/Unit 7': float,
        'Slide Purchase Pc/Unit 7': float,
        'Slide Production LT 7': float,
        'Slide Days TS 7': float,
        'Slide Qty 8': float,
        'Slide Sales Pc/Unit 8': float,
        'Slide Purchase Pc/Unit 8': float,
        'Slide Production LT 8': float,
        'Slide Days TS 8': float,
        'Slide Qty 9': float,
        'Slide Sales Pc/Unit 9': float,
        'Slide Purchase Pc/Unit 9': float,
        'Slide Production LT 9': float,
        'Slide Days TS 9': float,
        'Slide Qty 10': float,
        'Slide Sales Pc/Unit 10': float,
        'Slide Purchase Pc/Unit 10': float,
        'Slide Production LT 10': float,
        'Slide Days TS 10': float,
        'Unit Price Check': str,
        'Express T Calc Type for Sales': str,
        'Express T Sales Pc/Unit': float,
        'Express T Purchase Pc/Unit': float,
        'Express A Calc Type for Sales': str,
        'Express A Sales Pc/Unit': float,
        'Express A Calc Type for Purchase': str,
        'Express A Purchase Pc/Unit': float,
        'Express A Production LT': float,
        'Special Express A Calc Type for Sales': str,
        'Special Express A Sales Pc/Unit': float,
        'Plant Express A Purchase Calc': str,
        'Plant Express A Purchase Pc/Unit': float,
        'Express B Calc Type for Sales': str,
        'Express B Sales Pc/Unit': float,
        'Express B Purchase Pc/Unit': float,
        'Express B Production LT': float,
        'Express C Calc Type for Sales': str,
        'Express C Sales Pc/Unit': float,
        'Express C Purchase Pc/Unit': float,
        'Express C Production LT': float,
        'Weight': float,
        'Weight Calc Mode': str,
        'Weight Coefficient': float,
        'Weight Calc': str,
        'Classify Code': str,
        'Launch Date': str,
        'Prod Mst for Alt Supplier': str,
        'Supplier Code': str,
        'Spec Condition Code': str,
        'Ordering Message Code': str,
        'Alt Dsct Rt:S 1': float,
        'Alt Dsct Rt:P 1': float,
        'Alt Dsct Rt:S 2': float,
        'Alt Dsct Rt:P 2': float,
        'Alt Dsct Rt:S 3': float,
        'Alt Dsct Rt:P 3': float,
        'Alt Dsct Rt:S 4': float,
        'Alt Dsct Rt:P 4': float,
        'Alt Dsct Rt:S 5': float,
        'Alt Dsct Rt:P 5': float,
        'Alt Dsct Rt:S 6': float,
        'Alt Dsct Rt:P 6': float,
        'Alt Dsct Rt:S 7': float,
        'Alt Dsct Rt:P 7': float,
        'Alt Dsct Rt:S 8': float,
        'Alt Dsct Rt:P 8': float,
        'Alt Dsct Rt:S 9': float,
        'Alt Dsct Rt:P 9': float,
        'Alt Dsct Rt:S 10': float,
        'Alt Dsct Rt:P 10': float,
        'Product Special Flg': str,
        'Country Of Origin': str,
        'Discontinued on Date': str,
        'Production Days Calc Opt': str,
        'SO Suspension': str,
        'Abolishment MSG': str,
        'Product Group Code': str,
        'BU Code': str,
        'Qty / Order': float,
        'Each Time QT': str,
        'Product Delivery': str,
        'Packing List Delivery': str,
        'PO Format Div': str,
        'SO Cancel Charge Rate': float,
        '1st Day After SO Cancel Charge Rate': float,
        '3rd Days After SO Cancel Charge Rate': float,
        'Production LT for STOCK': float,
        'Developed on Date': str,
        'CSS Div': str,
        'Pressure Div': str,
        'Pressure Length': float,
        'Tax Free Div': str,
        'Dsct Rt :Sales': float,
        'Dsct Rt :Purchase': float,
        'Product LT of ExpZ': float,
        'Supplier Code of ExpZ': str,
        'Direct Ship (ref Check Mst)': str,
        'Production Days Count': str,
        'Reorder level Logic': str,
        'MTO Calc': str,
        'Period': float,
        'Safety': float,
        'Heavy Product': str,
        'Expensive Product Div': str,
        'Heavy Threshold': float,
        'Expensive Threshold': float,
        'Cutoff Time for Direct': str,
        'Cutoff Time for 1day MTO': str,
        'Limited MBO Product': str,
        'Minimum Charge': str,
        'Max Qty 1': float,
        'Amount 1': float,
        'Max Qty 2': float,
        'Amount 2': float,
        'Qty / Pack': float,
        'Brand Code': str,
        'Qty / Purchase': float,
        'PO Product Code': str,
        'Currency(Sales) Code': str,
        'Currency(Purchase) Code': str,
        'Purchase Mode': str,
        'HS Code': str,
        'Product Name': str,
        'Native Product Name': str,
        'IO Supply Means': str,
        'IO Supply Means (URG)': str,
        'Days to Ship on Catalog': float,
        'Express T Production LT': float,
        'Express T Days TS': float,
        'Express A Days TS': float,
        'Express B Days TS': float,
        'Express C Days TS': float,
        'Print Weight Unit': str,
        'Days to Ship of ExpZ': float,
        'Currency(Purchase of BO)': str,
        'Purchase Mode of BO': str,
        'Shipment Stop Div': str,
        'Express A Direct Ship Flg': str,
        'Express B Direct Ship Flg': str,
        'Express C Direct Ship Flg': str,
        'Express T Direct Ship Flg': str,
        'Apply TI to Plant 1': str,
        'Cutoff Time for TI to Plant 1': str,
        'Apply TI to Plant 2': str,
        'Cutoff Time for TI to Plant 2': str,
        'Apply TI to Plant 3': str,
        'Cutoff Time for TI to Plant 3': str,
        'Apply TI to Plant 4': str,
        'Cutoff Time for TI to Plant 4': str,
        'Apply TI to Plant 5': str,
        'Cutoff Time for TI to Plant 5': str,
        'Apply TI to Plant 6': str,
        'Cutoff Time for TI to Plant 6': str,
        'Apply TI to Plant 7': str,
        'Cutoff Time for TI to Plant 7': str,
        'Apply TI to Plant 8': str,
        'Cutoff Time for TI to Plant 8': str,
        'Apply TI to Plant 9': str,
        'Cutoff Time for TI to Plant 9': str,
        'Distribution Flg': str,
        'PO as STOCK': str,
        'Remarks': str,
        'Hazardous Product': str,
        'GTI Apply': str,
        'Message Mst to Imp Sub': str,
        'Print Qty Unit': str,
        'QC Product': str,
        'Partial Delivery Threshold': float,
        'Express L Calc Type for Sales': str,
        'Express L Message Code': str,
        'Express L Supplier Code': str,
        'Express L Dsct Rt:S 1': float,
        'Express L Dsct Rt:P 1': float,
        'Express L Slide Days 1': float,
        'Express L Dsct Rt:S 2': float,
        'Express L Dsct Rt:P 2': float,
        'Express L Slide Days 2': float,
        'Express L Dsct Rt:S 3': float,
        'Express L Dsct Rt:P 3': float,
        'Express L Slide Days 3': float,
        'Express L Dsct Rt:S 4': float,
        'Express L Dsct Rt:P 4': float,
        'Express L Slide Days 4': float,
        'Express L Dsct Rt:S 5': float,
        'Express L Dsct Rt:P 5': float,
        'Express L Slide Days 5': float,
        'Express L Dsct Rt:S 6': float,
        'Express L Dsct Rt:P 6': float,
        'Express L Slide Days 6': float,
        'Express L Dsct Rt:S 7': float,
        'Express L Dsct Rt:P 7': float,
        'Express L Slide Days 7': float,
        'Express L Dsct Rt:S 8': float,
        'Express L Dsct Rt:P 8': float,
        'Express L Slide Days 8': float,
        'Express L Dsct Rt:S 9': float,
        'Express L Dsct Rt:P 9': float,
        'Express L Slide Days 9': float,
        'Express L Dsct Rt:S 10': float,
        'Express L Dsct Rt:P 10': float,
        'Express L Slide Days 10': float})
    return type_p
if __name__ == "__main__":
    print(type())
